language: python

python:
  - "2.6"
  - "2.7"

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm
  - pip install pylint ordereddict pyyaml mysqlclient

before_script:
  - if [[ $TRAVIS_TAG == apptuit-v* ]]; then PACKAGE_VERSION=${TRAVIS_TAG#apptuit-v}; fi
    - echo $TRAVIS_TAG
    - echo $PACKAGE_VERSION

script:
  - ./pylint-runner.py -s
  - ./tests.py
  - cd rpm; make; cd ..
  - cd deb; make; cd ..


before_deploy:
    - if [[ "$PACKAGE_VERSION" != "" ]]; then
        PACKAGE_DATE=$(git log -1 --pretty="format:%ad" $TRAVIS_TAG --date=short);
        echo $PACKAGE_DATE;
        sed -ei 's/@PACKAGE_DATE@/$(PACKAGE_DATE)/' deb/bintray-descriptor.json;
        sed -ei 's/@PACKAGE_VERSION@/$(PACKAGE_VERSION)/' deb/bintray-descriptor.json;
        cat deb/bintray-descriptor.json;
      fi

deploy:
  - provider: bintray
    file: "deb/bintray-descriptor.json"
    user: "$BINTRAY_USER"
    key: "$BINTRAY_API_KEY"
    on:
      tags: true
      condition: "$PACKAGE_VERSION" != "" && "$BINTRAY_API_KEY" != ""