#!/bin/sh
#
# xcollector   Startup script for the xcollector monitoring agent
#
# chkconfig:   2345 15 85
# description: XCollector - Data collection agent for apptuit.ai
# processname: xcollector
# pidfile: /var/run/xcollector/xcollector.pid
#
### BEGIN INIT INFO
# Provides:          xcollector
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: XCollector - Data collection agent for apptuit.ai
### END INIT INFO

BASE_NAME=`basename $0`
PROG_NAME=${PROG_NAME-"$BASE_NAME"}
INSTALL_DIR=/usr/local/xcollector
WORKING_DIR=${WORKING_DIR-"$INSTALL_DIR"}
COLLECTORS_DIR=${WORKING_DIR}/collectors
YAML_CONF_DIR=${WORKING_DIR}/conf
#RUN_AS_USER=
#RUN_AS_GROUP=

PYTHONPATH="$PYTHONPATH:${COLLECTORS_DIR}/.."
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON="${INSTALL_DIR}/xcollector.py"
EXTRA_TAGS=""

. /lib/lsb/init-functions

if [ -r /etc/default/xcollector ]; then
    . /etc/default/xcollector
fi

PIDFILE=${PIDFILE-"/var/run/xcollector/$PROG_NAME.pid"}
LOGFILE=${LOGFILE-"/var/log/xcollector/$PROG_NAME.log"}
THIS_HOST=`hostname`
RUN_AS_USER=${RUN_AS_USER-"xcollector"}
RUN_AS_GROUP=${RUN_AS_GROUP-"xcollector"}

EXTRA_TAGS_OPTS=""
for TV in $EXTRA_TAGS; do
    EXTRA_TAGS_OPTS=${EXTRA_TAGS_OPTS}" -t ${TV}"
done

sanity_check() {
  for file in "$PIDFILE" "$LOGFILE"; do
    parentdir=`dirname "$file"`
    if [ ! -d "$parentdir" ]; then
      install -m 755 -o $RUN_AS_USER -g $RUN_AS_GROUP -d $parentdir
    fi
  done
}

case $1 in
    start)
        log_daemon_msg "Starting $PROG_NAME"
        sanity_check || return $?
        find "$COLLECTORS_DIR" -name '*.pyc' -delete

        taskset=""
        if [ -n "$CPU_LIST" ]; then
            if which taskset &>/dev/null; then
                taskset="taskset -c $CPU_LIST"
            else
                log_warning_msg "taskset not found, $PROG_NAME can't be"
                    " pinned to $CPU_LIST"
            fi
        fi

        PYTHONPATH=$PYTHONPATH $taskset start-stop-daemon --start --quiet -u $RUN_AS_USER\
            --pidfile "$PIDFILE" --chuid $RUN_AS_USER:$RUN_AS_GROUP\
            --startas $DAEMON -- \
            -t host=$THIS_HOST \
            -P "$PIDFILE" \
            -c $COLLECTORS_DIR -y $YAML_CONF_DIR --logfile $LOGFILE --daemonize $EXTRA_TAGS_OPTS

        log_end_msg $?
        ;;

    stop)
        log_daemon_msg "Stopping $PROG_NAME"
        if [ ! -f "$PIDFILE" ]; then
            log_failure_msg "$PIDFILE doesn't exist. $PROG_NAME not running?"
            exit 0
        fi
        start-stop-daemon --stop --retry 30 --quiet --oknodo -u $RUN_AS_USER --pidfile "$PIDFILE" && rm -f "$PIDFILE"
        rv=$?
        log_end_msg 0
        exit $rv
        ;;
    restart|force-reload)
        $0 stop && $0 start
        ;;

    status)
        status_of_proc -p $PIDFILE "$DAEMON" "$PROG_NAME"
        exit $?
        ;;

    *)
        echo "Usage: $PROG_NAME {start|stop|restart|force-reload|status}"
        exit 2
        ;;
esac
